FROM nginx:alpine
COPY app.html /usr/share/nginx/html/ 
COPY index.html /usr/share/nginx/html/ 
COPY styles.css /usr/share/nginx/html/
COPY styles_login.css /usr/share/nginx/html/
COPY login.svg /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY login.js /usr/share/nginx/html/
